"""Agregar columnas vendidas_dia y valor_vendido_dia

Revision ID: 276246edce06
Revises: 99a3cc13e005
Create Date: 2025-10-15 15:04:05.268175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276246edce06'
down_revision = '99a3cc13e005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendidas_dia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_vendido_dia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('valor_vendido_dia')
        batch_op.drop_column('vendidas_dia')

    # ### end Alembic commands ###
