"""Actualizar modelo LiquidacionProducto con nuevos campos

Revision ID: 68fae1f9aee6
Revises: 
Create Date: 2025-11-12 17:16:01.043187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fae1f9aee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventas_dia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('entradas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salidas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('caja_dia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('caja_total', sa.Float(), nullable=True))
        batch_op.drop_column('entrada_inventario')
        batch_op.drop_column('salida_efectivo')
        batch_op.drop_column('caja_actual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caja_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salida_efectivo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entrada_inventario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('caja_total')
        batch_op.drop_column('caja_dia')
        batch_op.drop_column('salidas')
        batch_op.drop_column('entradas')
        batch_op.drop_column('ventas_dia')

    # ### end Alembic commands ###
