"""Inicializar base de datos

Revision ID: 99a3cc13e005
Revises: 
Create Date: 2025-09-22 21:41:13.616372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a3cc13e005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_inicial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unidades_restantes', sa.Integer(), nullable=True))
        # valor_unitario con valor por defecto temporal para evitar error NOT NULL
        batch_op.add_column(sa.Column('valor_unitario', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('interes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('precio')

    # ### end Alembic commands ###

    # quitar el valor por defecto después de poblar la columna
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('valor_unitario', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('codigo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('fecha')
        batch_op.drop_column('interes')
        batch_op.drop_column('valor_unitario')
        batch_op.drop_column('unidades_restantes')
        batch_op.drop_column('stock_inicial')

    # ### end Alembic commands ###
